# Generated by Django 5.1.6 on 2025-03-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemId', models.IntegerField(unique=True)),
                ('Amount', models.IntegerField()),
                ('Name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
