# Generated by Django 5.1.6 on 2025-03-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='Name',
        ),
    ]
